### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by Cookzenberg** [Uintra/Uintra#10]
Hi

What is the best practice for rebranding Uintra so that it doesn't get overwritten during upgrades?

I had amended some of the CSS files directly and repackaged them with webpack in 0.5 but these changes were overwritten during the upgrade to 1.0.0.1.

Should I edit the grid page template to reference my own stylesheet and manage that through the Umbraco admin panel?

Thanks
Andy

**Comment by DenysDzhel** [comment]
Hi, you can add your files or do any changes outside App_Plugins folder.

**Comment by Cookzenberg** [comment]
So just to confirm I can load up a stylesheet in a folder of my in inside the solution, and then change the grid page template to reference that?

Will I need to edit the grid page template after each release to reapply the stylesheet?

**Comment by DenysDzhel** [comment]
You don't need to edit grid template page at all.

You can use existing file '/Content/css/styles.css' for adding a styles.

Or if you need to you can create new css file and import it in one of two entry poins './Content/head_css.js' or './Content/main.js' webpack automatically will puts new styles in a bundle.

**Comment by Cookzenberg** [comment]
Ok thanks... I was still a little unclear what gets overwritten by the Nuget upgrade and what gets left behind.

**Comment by cdecinkoKnight** [comment]
What about postcss.config.js?  How do changes to these variables get applied?  Will this be overwritten by an upgrade?
