### ISSUE TITLE
Status on release 2.0

### ISSUE THREAD

**Issue by jpkeisala** [Uintra/Uintra#100]
I just bump into your project. I noticed that you have active commits on Release/2.0 branch which I assume is for Umbraco 8. But on Nuget only found 1.4 for Umbraco 7. 
I am running Umbraco 8. Is it a good idea to fork 2.0 or is it far from being able to do anything with it?

**Comment by denprodan** [comment]
Hi @jpkeisala. 
Correct, we are finishing Relese 2.0, if you have time to wait it's better to wait public release. 
We are planning to release it in a month

**Comment by janpluta** [comment]
Its two months after your posted "We are planning to release it in a month".  So when are you going to finish release 2.0 ?
