### ISSUE TITLE
Problems after install Uintra 1.4.0.0

### ISSUE THREAD

**Issue by jandersonfcosta** [Uintra/Uintra#106]
Hello!,

I'm new and I'm meeting Uintra now.
After installing Uintra following exactly the guide on this page https://github.com/Uintra/Uintra, I started using it to test.

Tests:
  - Post and edit newsletters
  - Post and edit news
  - Post and edit events
  - Add likes and other tests

What happens:
Whenever I perform any of these actions, it happens with extreme delay.
Another thing that happens for example, is that when you like, the page icon does not change automatically, it takes a long time.

See this [Add like](https://raw.githubusercontent.com/jandersonfcosta/MyPage1/master/add%20like.png)

Note: I did not install elasticsearch, could it be the cause of the delays?

Could you help me?

Server settings:
  - Windows 10 Enterprise 64x Trial or Windows Server 2012 Standard 64x Trial
  - IIS 10
  - SQL Server 2017 Express 64x
  - Visual Studio 2017 Community 64x
  - Google Chrome

Another question, is it possible to change the language of the Uintra website (end user) to Portuguese?

Sorry for my English, I'm Brazilian.
Thank you!

**Comment by denprodan** [comment]
Hi there @jandersonfcosta 
Welcome to community)
It looks like you missed Elasticsearch installation step. See https://docs.uintra.com/installing-uintra/v1.4.0/ point 3.8.
Yes, you can translate labels in whatever language you want. Use Localization section in Umbraco

**Comment by jandersonfcosta** [comment]
Thanks Denis, so the cause of the delays is the absence of elasticsearch?

**Comment by denprodan** [comment]
Yes. Correct

вт, 9 июн. 2020 г., 22:15 jandersonfcosta <notifications@github.com>:

**Comment by jandersonfcosta** [comment]
Hi Denis,

It worked after installing elasticsearch 5.2.1.
The delays stopped.
In my case, using Windows Server 2012 R2.

Thanks!
