### ISSUE TITLE
Uintra Members - Active Directory Integration

### ISSUE THREAD

**Issue by jandersonfcosta** [Uintra/Uintra#107]
Hello!

Can anyone show the best way to configure uintra so that members can connect using an Active Directory username and password?

At Uintra Documentation > Getting Started > Membership Integration
(https://docs.uintra.com/getting-started/membership-integration/v1.4.0), the guide says to overwrite IntranetUserServiceBase.cs, but I haven't found this class.

What is the best way?
Any guide?

Thank you!

**Comment by denprodan** [comment]
Hi @jandersonfcosta. If you want to login via Active Directory first of all you have to onboard all AD members to Umbraco Members.
IntranetUserServiceBase I believe now is 
IntranetMemberServiceBase

**Comment by jandersonfcosta** [comment]
Hi Denis,

**IntranetUserServiceBase** does not exist.
I didn't find any clear documentation anywhere.
Could you help me with a guide, tutorial, link to a solved case of any forum, anything ..
I've tried using some third party packages, but they don't work.

I'm almost giving up on uintra.

**Comment by GGesheva** [comment]
I am also curious about the integration with CustomMemberShipProvider, would be amazing if there is more information how this can be achieved. 

https://github.com/Uintra/Uintra/blob/master/src/uIntra.Users/DefaultImplementation/IntranetMemberServiceBase.cs#L208

**Comment by vmatsukatov** [comment]
dear @jandersonfcosta  and @GGesheva  sorry for that late answer, we will check documentation and update you with details asap. just in full speed of new Uintra based on Umbraco 8 releasing as a beta now
