### ISSUE TITLE
Error when adding event via umbraco

### ISSUE THREAD

**Issue by janpluta** [Uintra/Uintra#108]
When I want to add Event from Umbraco I am getting error, but when I am adding it from uintra everything is working.
![Screenshot_9](https://user-images.githubusercontent.com/64965614/85566157-124dde80-b630-11ea-9c0e-622724765031.png)

**Comment by vmatsukatov** [comment]
@1nsolenT  will you look and answer here just you have time from development Uintra 2.0 :) ?
