### ISSUE TITLE
Umbraco 8 Port?

### ISSUE THREAD

**Issue by mirkomaty** [Uintra/Uintra#109]
Are there any plans to port UIntra to Umbraco 8? Any supporters?

I might support porting. This depends on whether we receive an order from a customer.

Cheers Mirko

**Comment by denprodan** [comment]
Hi @mirkomaty 
Yes. We are in full speed of moving to U8
See release/2.0 branch
We have already made predictions about this, but they did not come true because of the high load on other projects

**Comment by mirkomaty** [comment]
Hi @denprodan, 
thanks a lot for your answer. I haven't noticed that there are newer commits in another branch. If the conversations with our customer go according to plan, then I will come back to you and offer help, if only to test.

**Comment by xcameleonx** [comment]
@denprodan Any update to this? I am working on a new project and this would be a perfect jumping off point, and the end users are pretty set on using V8 of Umbraco.

**Comment by vmatsukatov** [comment]
hi @xcameleonx  really sorry for delay, we plan to release Uintra 2.0 - beta version next week (33) as the latest

**Comment by cdecinkoKnight** [comment]
Please let us know ASAP when the website is updated. I need ammunition to sell this to the bosses and want to pitch them v2.

**Comment by vmatsukatov** [comment]
@cdecinkoKnight  @xcameleonx @mirkomaty  FYI Uintra 2.0.0 beta (based on Umbarco 8) is available here https://www.nuget.org/packages/uIntra/2.0.0-beta and in github also.

**Comment by cdecinkoKnight** [comment]
Is this using Framework or Core? Any updated install instructions?


Connie DeCinko
Sr. Full Stack Developer
Web and Mobile Development

Knight Transportation, Inc. | Phoenix, AZ
Connie.DeCinko@knighttrans.com<mailto:Connie.DeCinko@knighttrans.com>

[cid:image001.png@01D6707D.697ED130]

**Comment by vmatsukatov** [comment]
@cdecinkoKnight  it is using Framework, beause Umbraco 8 is not .net core

**Comment by vmatsukatov** [comment]
@cdecinkoKnight  it is the same version of elastic should be used, as it stays in install instruction for Uintra 1.*

**Comment by xcameleonx** [comment]
@vmatsukatov 5.2.1? That version is listed as past EOL support, and may be removed at any time. Are there any plans to upgrade this dependency?

**Comment by denprodan** [comment]
Hi @xcameleonx 
Current version left because of lack of time
We are planning to update Elastic to latest version in 2.1 or 2.2
