### ISSUE TITLE
How to run the project if the source code is downloaded from github?

### ISSUE THREAD

**Issue by ultimaUser500** [Uintra/Uintra#110]
I want to run the source code downloaded from github. What things should i think about? Right now I can not restore the nuget packages. It is complaining about some nuget packages not found.

**Comment by denprodan** [comment]
Hi @ultimaUser500. Could you please provide more information? From which branch you have downloaded the source and what packages not found?

**Comment by ultimaUser500** [comment]
I am trying to run release 2 as I want to run in Umbraco 8. Almost all compent.* packages can not be found. 
![image](https://user-images.githubusercontent.com/68706297/88455204-badfa000-ce73-11ea-8e26-4ddd20083607.png)

**Comment by denprodan** [comment]
Unfortunately, Release 2 still in progress and some packages not published

сб, 25 июл. 2020 г., 13:38 ultimaUser500 <notifications@github.com>:

**Comment by ultimaUser500** [comment]
Thank you
