### ISSUE TITLE
500 Error Trying to launch new install of Uintra 2

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#111]
I have completed the install of the 2.0.0 beta. When I launch for the first time in the browser I get this error:

HTTP Error 500.19 - Internal Server Error
Error Code | 0x8007000d

The error indicates an issue with the web.config however nothing appears to be out of the ordinary.

Running on Windows 10 desktop with IIS v10 using Chrome.

**Comment by xcameleonx** [comment]
Also getting this issue with a fresh project and database.

**Comment by denprodan** [comment]
Hi @cdecinkoKnight  and @xcameleonx. If it's possible could you please record the video of installation an error. That's would be super usefull

**Comment by cdecinkoKnight** [comment]
I did ANOTHER clean install and made sure just in case to install ElasticSearch. Fire up the site for the first time (local machine with IIS) and get a 500 error.

![image](https://user-images.githubusercontent.com/46462212/90538203-13ccec00-e133-11ea-9315-c633f2fb5bab.png)

**Comment by cdecinkoKnight** [comment]
Ok, figured this one out. You need to have URL Rewrite (https://www.iis.net/downloads/microsoft/url-rewrite) installed. Once I did that no more error and the site loads.  Would be nice if the Uintra or Umbraco installer checked for that.
