### ISSUE TITLE
Broken notifications label

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#115]
v2 Beta

Getting code rather than the Notifications label:

![image](https://user-images.githubusercontent.com/46462212/90548277-8cd34000-e141-11ea-8bb2-cf7d2abf0743.png)

**Comment by vmatsukatov** [comment]
Hi. there is labels management control in Umbraco for admin. just go there, search that label and set appropriated text. the idea is, all textx in the system are manageable by webmasetr and webmaster is in charge to support them
