### ISSUE TITLE
 Query: Adding new activities in Uintra

### ISSUE THREAD

**Issue by xcameleonx** [Uintra/Uintra#118]
"Dear Thomas

Thanks for your request. Could I ask you to create the question on github?"

So here it is.

We are looking at Uintra as a base for a project we are working on, and some questions I can’t seem to answers to. How to create new activity types. Is this possible? Is it just a case of basing it off the implementation of an existing activity, like Event, which looks pretty involved as it is? As for permissions, I see in the code from Github that the permissions are managed in a database migration, would it be simple enough for end users to extend these migrations and add additional permissions ad user groups on top of the three existing ones? We have installed Uintra from NuGet and are looking to extend it, if we want to extend, do we need to fork and then install to Umbraco manually?

**Comment by vmatsukatov** [comment]
@1nsolenT  could you help with details here ?

**Comment by xcameleonx** [comment]
Any update?

**Comment by 1nsolenT** [comment]
HI @xcameleonx , yes, we have a plan to make it possible by extending existing classes, implementing specific interfaces and so on in next releases (for now even IoC class compiled to assembly and you could not manage any dependencies). Another way, as you said before - to make a fork :)

**Comment by xcameleonx** [comment]
> 
> 
> HI @xcameleonx , yes, we have a plan to make it possible by extending existing classes, implementing specific interfaces and so on in next releases (for now even IoC class compiled to assembly and you could not manage any dependencies). Another way, as you said before - to make a fork :)

Is this the NinjectWebCommon.cs IoC config? Because that gets added to the project when you install Uintra, and is fully visible and editable by end users, I've compared the one in the source here in Github to the one that gets added to the project, and they are identical. Is the main problem of extending and creating new activities because a lot of the configuration is managed by the type enums, and implementing new ones could be an issue?

**Comment by 1nsolenT** [comment]
Oh, sorry, i thought you ask about Uintra 2.0 (beta). As for Uintra 1.0 yes, you can use this file to manage your custom dependencies. If you want to add some new activity types to Uintra, you need to create a new Enum with new activity type and register it like here `RegisterTypeProvider<IActivityTypeProvider, ActivityTypeProvider>(typeof(IntranetActivityTypeEnum), typeof(CUSTOMIntranetActivityTypeEnum));` , after that you will need a service for this activity and so on.

**Comment by xcameleonx** [comment]
> 
> 
> Oh, sorry, i thought you ask about Uintra 2.0 (beta). As for Uintra 1.0 yes, you can use this file to manage your custom dependencies. If you want to add some new activity types to Uintra, you need to create a new Enum with new activity type and register it like here `RegisterTypeProvider<IActivityTypeProvider, ActivityTypeProvider>(typeof(IntranetActivityTypeEnum), typeof(CUSTOMIntranetActivityTypeEnum));` , after that you will need a service for this activity and so on.

I've tried doing this, and when I run I'm getting a NullReferenceException in the BulletinService

`   at Compent.Uintra.Core.Feed.Links.ActivityLinkService.GetLinks(Guid activityId)
   at Compent.Uintra.Core.Bulletins.BulletinsService.Map(Bulletin bulletin)
   at System.Linq.Enumerable.WhereSelectListIterator'2.MoveNext()
   at System.Linq.Enumerable.<SelectIterator>d__5'2.MoveNext()
   at System.Linq.Lookup'2.Create[TSource](IEnumerable'1 source, Func'2 keySelector, Func'2 elementSelector, IEqualityComparer'1 comparer)
   at System.Linq.GroupedEnumerable'3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator'2.MoveNext()
   at Uintra.Search.ElasticSearchRepository'1.Save(IEnumerable'1 documents)
   at Compent.Uintra.Core.UserTags.Indexers.ElasticUintraActivityIndex.Index(IEnumerable'1 activities)
   at Compent.Uintra.Core.Bulletins.BulletinsService.FillIndex()
   at Compent.Uintra.Core.Bulletins.BulletinsService.UpdateCache()
   at Uintra.Core.Activity.IntranetActivityService'1.GetAll(Boolean includeHidden)
   at Uintra.Core.Activity.IntranetActivityService'1.GetManyActual()
   at Compent.Uintra.Core.Bulletins.BulletinsService.GetOrderedActualItems()
   at Compent.Uintra.Core.Bulletins.BulletinsService.GetItems()
   at Compent.Uintra.Core.CentralFeed.CentralFeedService.<>c.<GetFeed>b__3_0(IFeedItemService service)
   at System.Linq.Enumerable.<SelectManyIterator>d__17'2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator'1.MoveNext()
   at System.Linq.Buffer'1..ctor(IEnumerable'1 source)
   at System.Linq.OrderedEnumerable'1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable'1 source)
   at Compent.Uintra.Controllers.CentralFeedController.GetCentralFeedItems(Enum type)`

I've created an custom enum
`ExtendedIntranetActivityTypeEnum
    {
        News = IntranetActivityTypeEnum.News,
        Events = IntranetActivityTypeEnum.Events,
        Bulletins = IntranetActivityTypeEnum.Bulletins,
        PagePromotion = IntranetActivityTypeEnum.PagePromotion,
        ContentPage = IntranetActivityTypeEnum.ContentPage,
        CustomActivity= 1000
    }`

and used it in DI
`RegisterTypeProvider<IActivityTypeProvider, ActivityTypeProvider>(typeof(ExtendedIntranetActivityTypeEnum));`

I have a service for the custom activity, it's basically a clone of event for the moment. This is where I got to before reaching out to you guys, anything immediately obvious as the issue would be a massive help. I'm sure I'm pretty close to getting ti working, just need some helkp getting over that final hurdle.

Thanks.

**Comment by vmatsukatov** [comment]
@xcameleonx  we will discuss that again internally, and provide you code snippets as an example and more detailed info about overriding and new activity types creation, that was one of the most important logic we did in Uintra 1.* and also we of course will follow it in Uintra 2.* (again, we have here part of flexibility already, just should be finished)

Thanks, Vadym

**Comment by xcameleonx** [comment]
Thanks, much appreciated.

**Comment by vmatsukatov** [comment]
Hi @xcameleonx ,

after discussion with team, i can confirm that Uintra 1.* is ready for both, creation new activity types by inheritance from activity base and also, for extending and overriding for existing activities. in case of creation new, you of course need also to create not only backend part, but also front end part (by following and reusing existing activity type, e.g. news). and as we can see you are in the right way here. 

to help you with the issue above, we need more info though.

**Comment by xcameleonx** [comment]
Delisting of V1 packages stopped this from being completed. New developers and CI could not build as the packages could not be found on NuGet.
