### ISSUE TITLE
Member password self-service

### ISSUE THREAD

**Issue by Cookzenberg** [Uintra/Uintra#12]
Hi

I've knocked up a Change Password screen, and Forgot Password / Reset Password flow so that my members have self-service for their access to uIntra.

Are there plans to incorporate this functionality in the core product at some point?

I don't see it listed on the roadmap Denis kindly shared previously.

Thanks
Andy

**Comment by UintraContact** [comment]
Hi Andy,

as most of existing live Uintra instances, have memebrship from Active directory or others CRMs, that makes good sense to incorporate it, very good point! we will set it in pipe line for next releases ;)

Br,
Vadym
