### ISSUE TITLE
Latest version of UIntra references private/unfound Nuget packages

### ISSUE THREAD

**Issue by jkoletar** [Uintra/Uintra#121]
I downloaded the latest 2.0.0 version of Uintra and it fails to compile.  The Uintra project is referencing unavailable versions of supporting packages.  It looks like the needed version of the packages was not made available in Nuget.

![image](https://user-images.githubusercontent.com/2780829/96877096-d5a7bd80-143e-11eb-8ba6-7f2027b1c216.png)

**Comment by 1nsolenT** [comment]
Hi @jkoletar uintra.1.4.1 was not published to nuget. Please use latest version from nuget (Uintra.2.0.0). It is not possible for now to lunch source code locally for Uintra v.2.0.0+ (branch master or release/2.1) due to dependency on internal package (we are working on it).
