### ISSUE TITLE
Failed to install to virtual directory.

### ISSUE THREAD

**Issue by weerapongpruchya** [Uintra/Uintra#123]
Hi,

I created two virtual directories.
1. uSkinned Themes
2. Uintra

So I have two umbraco apps(1. uSkinned 2.Uintra)
if the application is installed on the server in a subfolder of the default website. It seems the paths will not work correctly.

![11-2-2020 1-24-00 PM](https://user-images.githubusercontent.com/73492977/97836618-45eff200-1d0f-11eb-8617-a9e48ad8becf.png)

Server Error in '/Uintra' Application.
Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.NullReferenceException: Object reference not set to an instance of an object.
  at Uintra20.Core.Updater.MigrationExecutor.Run()
  at Uintra20.UintraApplicationComponent.Initialize()
  at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 188
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Umbraco.Core.Exceptions.BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.NullReferenceException: Object reference not set to an instance of an object.
  at Uintra20.Core.Updater.MigrationExecutor.Run()
  at Uintra20.UintraApplicationComponent.Initialize()
  at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32
  at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 188

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[BootFailedException: Boot failed: Umbraco cannot run. See Umbraco's log file for more details.

-> Umbraco.Core.Exceptions.BootFailedException: Boot failed.

-> System.NullReferenceException: Object reference not set to an instance of an object.
   at Uintra20.Core.Updater.MigrationExecutor.Run()
   at Uintra20.UintraApplicationComponent.Initialize()
   at Umbraco.Core.Composing.ComponentCollection.Initialize() in D:\a\1\s\src\Umbraco.Core\Composing\ComponentCollection.cs:line 32
   at Umbraco.Core.Runtime.CoreRuntime.Boot(IRegister register, DisposableTimer timer) in D:\a\1\s\src\Umbraco.Core\Runtime\CoreRuntime.cs:line 188]
   Umbraco.Core.Exceptions.BootFailedException.Rethrow(BootFailedException bootFailedException) in D:\a\1\s\src\Umbraco.Core\Exceptions\BootFailedException.cs:80
   Umbraco.Web.<>c.<Init>b__18_0(Object sender, EventArgs args) in D:\a\1\s\src\Umbraco.Web\UmbracoInjectedModule.cs:369
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +201
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3535.0 

How to fix this?

Thanks,
Weera

**Comment by denprodan** [comment]
Hi @weerapongpruchya 
As I can see in this issue was the same error https://github.com/Uintra/Uintra/issues/120
Do you use IISExpress or SqlCompact?

**Comment by weerapongpruchya** [comment]
Hi Denis Prodan,

No, this is a live server with MS-SQL 2016-17. It was installed successfully with uSkinned(Umbraco) but failed with Uintra(Umbraco).
If installed on the root, no problems.

**Comment by weerapongpruchya** [comment]
Hi Denis Prodan, 
With a google search, there's many result but still don't know how to fix it.

System.TypeInitializationException: The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception. ---> System.ArgumentException: The virtual path '/' maps to another application, which is not allowed.\r\n   at System.Web.CachedPathData.GetVirtualPathData(VirtualPath virtualPath, Boolean permitPathsOutsideApp)\r\n   at System.Web.HttpContext.GetFilePathData()\r\n   at System.Web.HttpContext.GetConfigurationPathData()\r\n   at System.Web.HttpContext.GetSection(String sectionName)\r\n   at System.Web.Configuration.HttpConfigurationSystem.GetSection(String sectionName)\r\n   at

**Comment by vmatsukatov** [comment]
hi @weerapongpruchya 

apologize for the very late response, please, reopen that issue if still topical in the new Uintra version or in that you using still and we will do our best to provide you details to resolve it. we will close that issue for now as it is related with previous Uintra version.
