### ISSUE TITLE
Have you fixed these bugs for 2.0+

### ISSUE THREAD

**Issue by weerapongpruchya** [Uintra/Uintra#127]
Hi Uintra Team.

I found 2 issues 

First one belong to UI user Role.
![11-16-2020 9-25-13 AM](https://user-images.githubusercontent.com/73492977/99206545-3a5ff900-27ee-11eb-84eb-5a1d01fc31a3.png)

The second issue
![11-16-2020 9-26-42 AM](https://user-images.githubusercontent.com/73492977/99206623-77c48680-27ee-11eb-922a-45fefb4a0708.png)

https://github.com/Uintra/Uintra/issues/115

The label within the BackOffice won't solve the issue.

Best Regards,
Weera

**Comment by denprodan** [comment]
Hi @weerapongpruchya. Thanks for helping. I have created related issues in our internal system. They will be fixed in next release
