### ISSUE TITLE
Not able to run application after installation 

### ISSUE THREAD

**Issue by naveennspl** [Uintra/Uintra#128]
I have tried the link "https://github.com/Uintra/Uintra" reference for installation of UIntra. But after complete installation, I getting similar error on all actions by clicking the links in the application. I am not able to take any action in the UIntra application.

Please guide me in understanding what is the issue. Attaching logs along with the issue.

![image](https://user-images.githubusercontent.com/46313119/100982077-a328ce80-356d-11eb-8e8b-5db5f0d17e9a.png)

![image](https://user-images.githubusercontent.com/46313119/100982196-c2bff700-356d-11eb-852b-dc794b4ae526.png)

[Logs.zip](https://github.com/Uintra/Uintra/files/5634589/Logs.zip)

**Comment by denprodan** [comment]
Hi @naveennspl. Sorry for late answer. We have accidentally missed this issue. Is this still actual for you?
