### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by Sirca19** [Uintra/Uintra#129]
Hello

I´m new with Umbraco, and now i have to develop an intranet, so i installed uintra.
I'm strugling to change the home page template..i also tried to create a new one, but it didnt work, because it allways shows the same one.

Is there any tutorial on how to change the homepage template on uintra?
Thanks

**Comment by denprodan** [comment]
Hi @Sirca19. 
Thanks for using Uintra
What exactly you need to change on the home page?
Take a look at Index.cshtml it's an base template where all content are rendering (`<app-root></app-root>`)
To apply changes run **nmp run build** in _Content_ folder

**Comment by Sirca19** [comment]
Hi

Thanks, I will try that. I want to change the top banner  and have one more navigation menu(horizontal) on it, from another template i downloaded. 

Anyway i will try to change the index.cstml for now. 

Thanks again

**Comment by Sirca19** [comment]
Hello Again

Like i did easily on Umbraco core, i tried to create a master template and associate the pages (ie home) to it, but with uintra it does not work...because nothing changes...is there another way to do this on uintra?.

Thanks

**Comment by denprodan** [comment]
Hi again 
Uintra works in another way with Umbraco content, we don't use Umbraco template
We are working on documentation
What version of Uintra do you use?

**Comment by Sirca19** [comment]
Hello

Ok thats why!! .. i installed 2.0 via visual studio

Thanks

**Comment by denprodan** [comment]
Hi @Sirca19 
Check this, maybe you will find some answers [here ](https://drive.google.com/file/d/1t5vUA18L09yoNUlbwCE7jEiyBVa0KDid/view?usp=sharing)

**Comment by Sirca19** [comment]
Hi

Thanks.. I will try it.

**Comment by weerapongpruchya** [comment]
Hi @denprodan 

Can't run npm run build.
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle uintra20@0.0.0~prebuild: uintra20@0.0.0
6 verbose lifecycle uintra20@0.0.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle uintra20@0.0.0~prebuild: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\_basicsite\xfanshop\xfanshop\content\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\thaicarrot\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\OPOS\Epson2;C:\Program Files\EPSON\OPOS for .NET\Lib;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Bitvise SSH Client;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\thaicarrot\AppData\Local\Programs\Fiddler;C:\Users\thaicarrot\AppData\Roaming\npm
8 verbose lifecycle uintra20@0.0.0~prebuild: CWD: E:\_basicsite\eDaybit\eDaybit\content
9 silly lifecycle uintra20@0.0.0~prebuild: Args: [ '/d /s /c', 'node ./build-support/before.js' ]
10 silly lifecycle uintra20@0.0.0~prebuild: Returned: code: 0  signal: null
11 info lifecycle uintra20@0.0.0~build: uintra20@0.0.0
12 verbose lifecycle uintra20@0.0.0~build: unsafe-perm in lifecycle true
13 verbose lifecycle uintra20@0.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\_basicsite\eDaybit\eDaybit\content\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Users\thaicarrot\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\OPOS\Epson2;C:\Program Files\EPSON\OPOS for .NET\Lib;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Bitvise SSH Client;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\thaicarrot\AppData\Local\Programs\Fiddler;C:\Users\thaicarrot\AppData\Roaming\npm
14 verbose lifecycle uintra20@0.0.0~build: CWD: E:\_basicsite\eDaybit\eDaybit\content
15 silly lifecycle uintra20@0.0.0~build: Args: [ '/d /s /c', 'ng build --prod --deploy-url /wwwroot/' ]
16 info lifecycle uintra20@0.0.0~build: Failed to exec build script
17 verbose stack Error: uintra20@0.0.0 build: `ng build --prod --deploy-url /wwwroot/`
17 verbose stack spawn ENOENT
17 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:48:18)
17 verbose stack     at ChildProcess.emit (events.js:315:20)
17 verbose stack     at maybeClose (internal/child_process.js:1048:16)
17 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
18 verbose pkgid uintra20@0.0.0
19 verbose cwd E:\_basicsite\eDaybit\eDaybit\content
20 verbose Windows_NT 6.3.9600
21 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
22 verbose node v14.16.1
23 verbose npm  v6.14.12
24 error code ELIFECYCLE
25 error syscall spawn
26 error file C:\Windows\system32\cmd.exe
27 error errno ENOENT
28 error uintra20@0.0.0 build: `ng build --prod --deploy-url /wwwroot/`
28 error spawn ENOENT
29 error Failed at the uintra20@0.0.0 build script.
29 error This is probably not a problem with npm. There is likely additional logging output above.
30 verbose exit [ 1, true ]

Any suggestion please advise, I am new with these

The typescripts installed

Thanks, And Best Regards,
Weera
[2021-05-03T06_33_14_856Z-debug.log](https://github.com/Uintra/Uintra/files/6413297/2021-05-03T06_33_14_856Z-debug.log)

**Comment by weerapongpruchya** [comment]
My issues fixed, It need specific package versions
f.e typescript 3.4.5 and npm i @angular-devkit/build-angular@0.803.24
