### ISSUE TITLE
Content Panel is not shown

### ISSUE THREAD

**Issue by Cookzenberg** [Uintra/Uintra#13]
Hi 

I followed the instructions from [issue 7](https://github.com/Uintra/Uintra/issues/7) to create a new permanent content page for my left hand navmenu.

None of the content panels I place on the page are rendered in HTML sent to the browser. The other content panels seem to be working okay. If I put a content, table, content and comments panel in sequence I only see the table and comments panels.

Is it possible I'm missing a setting that doesn't apply to the other panels? Or could you suggest where I might look in debug or logs to see what is going wrong for me?

I'm using version 1.0.0.1.

Thanks
Andrew

**Comment by denprodan** [comment]
Hi Cookzenberg.
Could you please sent screentshots of your Content Page and Content Panels in Umbraco and also screen of rendered content pagr on UI?

**Comment by Cookzenberg** [comment]
Hi Denis

I upgraded Umbraco to 1.1.0 (to try to test the user list sort - feedback in a while) and the problem does not occur any longer. The Content panels are displayed fine even though I didn't change any settings on those pages as part of the upgrade.

Thanks anyway
Andrew

**Comment by Cookzenberg** [comment]
In the interests of full disclosure I will say that my content-panel.cshtml was corrupted, probably during my experiments in changing the branding, and that is why it was not working. The new release overwrote my bad version.
