### ISSUE TITLE
Failed to install Uintra 2.1

### ISSUE THREAD

**Issue by weerapongpruchya** [Uintra/Uintra#130]
Hi Uintra Teams,

I just tested and didn't dig deep into the issues.

![3-22-2021 5-39-12 AM](https://user-images.githubusercontent.com/73492977/111923292-0b75ce80-8ad1-11eb-9c7f-9f31cf2a64f7.png)

Regards,
Weera

**Comment by denprodan** [comment]
Hi @weerapongpruchya
2.0.1? 
We didn't release this version

**Comment by weerapongpruchya** [comment]
Hi denprodan,

Sorry, Install-Package uIntra -Version 2.1.0

**Comment by denprodan** [comment]
Are you running it on IIS Express?

**Comment by weerapongpruchya** [comment]
No, not the IIS Express

**Comment by denprodan** [comment]
Could you please describe steps to reproduce?

**Comment by ksolberg** [comment]
We're facing the same issue. @denprodan : Did you find a solution?

Edit - followed the installation instructions on Github and it fails in step 4.3.

**Comment by denprodan** [comment]
Hi @ksolberg 
Unfortunately we can't reproduce this issue.
Do you have the same error as @weerapongpruchya?

**Comment by 1nsolenT** [comment]
You can get this error only if you named your project "Uintra". Just rename it and problem will be solved.
