### ISSUE TITLE
Nuget Install 2.1.0 - Failed to install System.Security.Cryptography.Encoding

### ISSUE THREAD

**Issue by rodes74** [Uintra/Uintra#133]
I tried to install the package via nuget.
The instalation starts but when is installing the System.Security.Cryptography.Encoding fails and revert the instalation process.
At the end throw an error saying that file is damaged.

Does anyone had this problem?

Best regards

**Comment by denprodan** [comment]
Hi @rodes74 
Do you choose Custom Machine Key during Umbraco installation?
![image](https://user-images.githubusercontent.com/25720118/117890176-59cb7080-b2bd-11eb-8f4d-e4df451451c4.png)

**Comment by rodes74** [comment]
Hi 

I don't reach umbraco instalatiion. I started  to install as indcated  here https://github.com/Uintra/Uintra.
Created a project and install uintra from nuget . The problem ocurred in Uintra install from nuget

I presume i have to install Umbraco after uintra , correct me if i'm wrong.

Best Regards.



> Hi @rodes74
> Do you choose Custom Machine Key during Umbraco installation?
> ![image](https://user-images.githubusercontent.com/25720118/117890176-59cb7080-b2bd-11eb-8f4d-e4df451451c4.png)

**Comment by denprodan** [comment]
Actually Umbraco/Uintra installation comes right after you run your app for the firts time
So do you get this error on nuget installation from Visual Studio or?
Can you share some screenshots?
Thanks in advance

**Comment by rodes74** [comment]
The error occurs on visual studio on the uintra nuget installation.
I already have another project with uintra instaled on my machine, but it is an older version and gives too many errors on umbraco backofffice

So i try to install the last version to see if that errorss disappear

The error seems to be on the nuget installation, after nuget trying to install System.Security.Cryptography.Encoding, this reference fails and revert the instalation process and remove the packages previous installed from nuget

**Comment by denprodan** [comment]
Do you try to update from 1.* to 2.* version?
Try to install latest vesrion on clean project
Unfortunatelly we haven't maintained upgrade from 1.* to 2.* versions because there are a lot of breaking changes related to Umbraco 8

**Comment by rodes74** [comment]
I tried an install on a clean project. 
I don't try the update my old project.

It was a clean install

**Comment by rodes74** [comment]
The only solution i have  was to download the nuget package System.Security.Cryptography.Encoding and install locally from a nuget folder i created and install it from there.
After that  i installed uintra package from nuget. 
And now completed the installation

**Comment by vmatsukatov** [comment]
hi @rodes74  thanks for update and that is great you have completed install.
