### ISSUE TITLE
Uintra has blocked existing website pages. 

### ISSUE THREAD

**Issue by arielamittest** [Uintra/Uintra#138]
I have installed uintra package and it has blocked my website existing pages. Now only uintra pages are working. 
I also noticed that backoffice urls are changed to without port number at localhost. And only one host name allowed on root.

Is there any way to fix it? So that I can run my existing pages as default working.
Currently I am trying to open other pages then only login page is showing.

**Comment by denprodan** [comment]
Hi @arielamittest 
That's possible because Uintra is the package that need to be installed on new project not existed
But if you give us more information, I believe we could work this out

**Comment by arielamittest** [comment]
Thanks for the reply @denprodan .

I have the existing website where I want to use Uintra package. Existing website has normal content pages which is coming from another package. So basically my need is existing pages should work as it is and if I open e.g. /uintra then only Uintra functionality should work.
Currently in the backoffice only one root is allowed for domain, if try to set domain on existing root node then uintra showing pages not published and if try to set domain on uintra then existing root node showing pages not published.

I also noticed one other issue if I tried to set domain e.g. http://localhost:12345 then its converted to http://localhost/

My root node structure is like this:

ExistingHomeNode (url should work here http://localhost:12345)
   page1
   page2

UintraHomeNode (url should work here http://localhost:12345/uintra)
 page1
 page2

-------------------------------------------
Uintra should work here if I try to open http://localhost:12345/uintra 
http://localhost:12345 here should be work as default existing pages


I think I have explained all.


Thanks.

**Comment by denprodan** [comment]
Hi @arielamittest
Unfortunatelly this approach when Uintra is not root of the website might take an enormous bunch of code customizations
We were developing Uintra as "classic Intranet" solution which required only one entry point
My suggestion to move Uintra to separate host and make redirections from your target site
You also can make anonymous pages on Uintra, we have https://github.com/Uintra/Uintra/tree/features/anonymous-pages branch where we make possibillity to create anonymous page. It's fully tested but not merged in the new version branch, you could move them as patch

**Comment by arielamittest** [comment]
Thanks for replay and suggestions.
