### ISSUE TITLE
Pages should scroll to top when navigating

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#18]
All of the pages should scroll to the top when moving to a new page or section of the site.  Currently users are dropped into the middle or end of a news list or other content.

**Comment by denprodan** [comment]
Hi decinkoKnight. Good point. Thanks. We will create appropriate task in our bug tracking system

**Comment by denprodan** [comment]
Hi @cdecinkoKnight 
We have launched Uintra v=1.2 where we fixed this issue. Could you please provide feedback?

**Comment by cdecinkoKnight** [comment]
Looks good.  Thanks.
