### ISSUE TITLE
Elastic search issue

### ISSUE THREAD

**Issue by VidarM** [Uintra/Uintra#19]

**Comment by Cookzenberg** [comment]
Hi Vidar, try adding this plugin to your Elasticsearch installation:

https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html

I had to do this separately last time I set up uIntra. I still don't know why I didn't need to do the same on earlier installs.

**Comment by denprodan** [comment]
Hi Vidar
Did you pointed Uintra to your local Elasticsearch in web.config?
![image](https://user-images.githubusercontent.com/25720118/50884678-51648180-13f4-11e9-904c-f25ab0397e15.png)

**Comment by VidarM** [comment]
> Hi Vidar, try adding this plugin to your Elasticsearch installation:
> 
> https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html
> 
> I had to do this as a separate step after installing Elasticsearch last time I set up uIntra. I still don't know why I didn't need to do the same on earlier installs.

Hi @Cookzenberg 

I tried now, but it say I need version 7 of elastic search, will UIntra work with this version of UIntra, I whought it only worked with version 5.2.1?

Best
Vidar

**Comment by VidarM** [comment]
> Hi Vidar
> Did you point Uintra to your local Elasticsearch in web.config?
> ![image](https://user-images.githubusercontent.com/25720118/50884678-51648180-13f4-11e9-904c-f25ab0397e15.png)

Hi @denprodan 

Yes that is why it say "http://79.xxx.xxxx.xxx"

Best
Vidar

**Comment by denprodan** [comment]
Could you please specify this index prefix name
and try to rebuild one more time?
![image](https://user-images.githubusercontent.com/25720118/50885435-6215f700-13f6-11e9-8a17-309decf526ad.png)

**Comment by Cookzenberg** [comment]
> > Hi Vidar, try adding this plugin to your Elasticsearch installation:
> > https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html
> > I had to do this as a separate step after installing Elasticsearch last time I set up uIntra. I still don't know why I didn't need to do the same on earlier installs.
> 
> Hi @Cookzenberg
> 
> I tried now, but it say I need version 7 of elastic search, will UIntra work with this version of UIntra, I whought it only worked with version 5.2.1?
> 
> Best
> Vidar

Try looking at the older versions of the ES docs and you should find the archives for previous release plugins. e.g I don't remember if this is the exact one I used but:

https://www.elastic.co/guide/en/elasticsearch/plugins/5.2/ingest-attachment.html

**Comment by VidarM** [comment]
> Hi Vidar
> Did you point Uintra to your local Elasticsearch in web.config?
> ![image](https://user-images.githubusercontent.com/25720118/50884678-51648180-13f4-11e9-904c-f25ab0397e15.png)

I have this already.

Best
Vidar

**Comment by VidarM** [comment]
> Could you please specify this index prefix name
> and try to rebuild one more time?
> ![image](https://user-images.githubusercontent.com/25720118/50885435-6215f700-13f6-11e9-8a17-309decf526ad.png)

I have this already.

Best
Vidar

**Comment by denprodan** [comment]
Did search work when it pointed to default elastic server?

**Comment by VidarM** [comment]
> Did search work when it was pointed to default elastic server?

This is an Azure installation, I do not have a default elastic server.

**Comment by denprodan** [comment]
We set up default elastic search server for our Uintra consumers 40.89.165.143:49200 just for search testing

**Comment by VidarM** [comment]
> 40.89.165.143:49200

What version did you install, and did you install any plugins?

**Comment by Cookzenberg** [comment]
Vidar, not sure if you noticed but I posted a link to the 5.2 version of the attachment plugin. I had exactly the same issue as you on my Azure hosted ES and the plugin solved it for me.

**Comment by denprodan** [comment]
> > 40.89.165.143:49200
> 
> What version did you install, and did you install any plugins?

5.2.1 It's standalone ES server

**Comment by VidarM** [comment]
I tried the 

> Vidar, not sure if you noticed but I posted a link to the 5.2 version of the attachment plugin. I had exactly the same issue as you on my Azure hosted ES and the plugin solved it for me.

I tride the plugin, but is say I need a plugin for 5.2.1, this plugin is for 5.2.2 so it did not start.

How where able to install the plugin?

**Comment by Cookzenberg** [comment]
I don't recall... I may have just used the plugin manager or I may have used the 5.1 version. I'll see if I can tell what version I have on my VM.

**Comment by VidarM** [comment]
> I don't recall... I may have just used the plugin manager or I may have used the 5.1 version. I'll see if I can tell what version I have on my VM.

Great, thanks! I tried the 5.1 version as well, and it did not start. I tried the plugin manager, and that one tried to install the latest version.

**Comment by Cookzenberg** [comment]
I find any downloaded files so it seems possible ran the command to ask the plugin manager to install it. 

Here are the files from my ES plugins folder:

[ingest-attachment.zip](https://github.com/Uintra/Uintra/files/2744739/ingest-attachment.zip)

I don't know if there is some other step required to manually register it with ES.

**Comment by VidarM** [comment]
> I find any downloaded files so it seems possible ran the command to ask the plugin manager to install it.
> 
> Here are the files from my ES plugins folder:
> 
> [ingest-attachment.zip](https://github.com/Uintra/Uintra/files/2744739/ingest-attachment.zip)
> 
> I don't know if there is some other step required to manually register it with ES.

Thank you. I tried this one but it did not work. 
One sidenote, I am using a windows server for this, are you on windows as well?

**Comment by Cookzenberg** [comment]
Yes I’m running ES on Windows VM in Azure.

**Comment by VidarM** [comment]
Strange.. When I try to add the plugins, I get an error in the log. If I delete all plugins except the Ingest Attachment, I get this error:

[2019-01-10T15:23:06,656][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [ingest-attachment-5.2.1.jar]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:295) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:131) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.node.Node.<init>(Node.java:297) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.2.1.jar:5.2.1]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.2.1.jar:5.2.1]
Caused by: java.nio.file.NoSuchFileException: C:\Program Files\elasticsearch\plugins\ingest-attachment-5.2.1.jar\plugin-descriptor.properties
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:?]

**Comment by VidarM** [comment]
> Yes I’m running ES on Windows VM in Azure.

How did you install it? I went to https://www.elastic.co/downloads/past-releases/elasticsearch-5-2-1 and downloaded the ZIP, extracted it into a folder under Program Files, and executed the intall service bat file, and started the service. 

This worked ok, no errors, but I was not able to connectd to elastic trough UIntra. I tried to install the plugin you had (ingest-attachment-5.2.1) by copying it to the plugin folder, and then restart the service. I then get the error from my previous post.

**Comment by VidarM** [comment]
Yes  @Cookzenberg 
I have also updated the config. And I can connect to it from the outside, so I know the elastic server is up and running and accessible from the Internet. But the problem is the plugin I guess. I tried to install it with the "install plugin" option, but this one fails with the "wrong version" as well.

Strange how difficult this should be.

**Comment by Cookzenberg** [comment]
What do you see when you run elasticsearch-plugin list?

**Comment by VidarM** [comment]
It has no plugins intalled. So the function "elasticsearch-plugin.bat list" returns empty

**Comment by Cookzenberg** [comment]
And your folder structure under elasticsearch? This is what mine looks like:

![image](https://user-images.githubusercontent.com/29954530/51029278-ca4b1100-158d-11e9-91b4-7fbeddba99c0.png)

**Comment by Cookzenberg** [comment]
Contents:

![image](https://user-images.githubusercontent.com/29954530/51029334-ed75c080-158d-11e9-9e19-ebdb6cb6b98c.png)

**Comment by Cookzenberg** [comment]
And plugin descriptor contents:

![image](https://user-images.githubusercontent.com/29954530/51029366-041c1780-158e-11e9-9892-178cb968e3a0.png)

**Comment by Cookzenberg** [comment]
In case that helps!

**Comment by VidarM** [comment]
Did you install these plugins yourself? Clean install on my machine, the plugin folder is empty.
Can you attach the ingest-attachment folder here?

**Comment by VidarM** [comment]
Ah, now i understood, I will try again.

Keeps you posted

**Comment by Cookzenberg** [comment]
Yep... use the folder I posted previously and stick the contents in the same place on your install as my images above. I don't see any other files inside ES that reference the plugin so hopefully the existence of the plugin in the right spot on the file system is all it takes.

**Comment by VidarM** [comment]
YES!!!!!! 
Got it working!! 

Thank you @Cookzenberg !!!!!

I will buy you a beer if/wheb we meet! <3

Best regards
Vidar

**Comment by Cookzenberg** [comment]
Good news on both counts.
:-)

**Comment by jandersonfcosta** [comment]
Thank you! helped me a lot!
