### ISSUE TITLE
Missing ComingEventViewModel controller

### ISSUE THREAD

**Issue by lautarobonetto** [Uintra/Uintra#22]
This view is calling a missing controller:
src/Compent.uIntra/App_Plugins/Events/ComingEvents/ComingEvents.cshtml

"Compent.Uintra.Controllers.ComingEventViewModel" doesn't existe on the solution.

Regards

**Comment by denprodan** [comment]
Hi lautarobonetto. Could you please post the whole stack trace?

**Comment by UintraContact** [comment]
Hi @lautarobonetto we consider this task as a closed, since we do not have your input here for more than 14 days, we hope you managed it and it works for you now. else, just reopen / add new issue
