### ISSUE TITLE
How to extend Edit Profile view

### ISSUE THREAD

**Issue by MiguelIPerez** [Uintra/Uintra#23]
I am developing some web site using uintra as a template, and, i get a new requirement that says that i have to redesign the edit view from what uintra has to something more detailed.

- Photo
- First Name
- Last Name
- College
- Carreer
- Tags
and so on...

I did know how to do it properly, so, I created pretty much everything from scratch, and, replaced the default uintra's Edit view to my own, but i am having a problem; **I am unable to edit the picture**, everytime i click save, the MediaRoot, Photo and NewMedia, are null in the model every  other data is there, except those properties, and i dont know how to pass it to the controller, do you have a how to about extending the edition view in order to fullfil the requirement?.

**Comment by denprodan** [comment]
Hi @MiguelIPerez. Could you please post your custom view, view model and control action. And we will try to figure out how to make it work:)

**Comment by MiguelIPerez** [comment]
EditProfile.cshtml

`@using System.Web.Mvc
@using System.Web.Mvc.Html
@using Uintra.Core.Controls.FileUpload
@using Uintra.Core.Extensions
@using Uintra.Notification.Configuration
@using Umbraco.Web
@model ProfileViewModel

<div id="js-profile-page" class="form profile-edit _profile">
    @using (Html.BeginUmbracoForm("EditProfile", "Profiler", FormMethod.Post))
    {
        @Html.HiddenFor(el => el.BasicModelData.Id)
        <div class="form__row clearfix">
            @{
                var additionClass = string.IsNullOrEmpty(Model.BasicModelData.Photo) ? "" : "_hide";
            }
            <div class="form__row clearfix @additionClass">
                <label class="form__label" for="file-upload">@Html.Localize("Profile.UploadNewPhoto.lbl")</label>
                @{
                    var settings = new FileUploadSettings { AllowedExtensions = ViewData["AllowedMediaExtensions"] as string, MaxFilesCount = 1 };
                    Html.RenderAction("Uploader", "FileUpload", new { Settings = settings });
                }
            </div>
            @if (!string.IsNullOrEmpty(Model.BasicModelData.Photo))
            {
                <div class="avatar avatar--square">
                    <img class="avatar__img" src="@Model.BasicModelData.Photo?width=100&height=100&mode=crop" width="100" alt="avatar" />

                    <span class="form__clear _clear-avatar icon-close js-delete-btn" data-confirm-message="@Html.Localize("Profile.DeletePhotoConfirm.lbl")" data-photo="@Model.BasicModelData.Photo"></span>
                </div>
            }

        </div>
        <div class="form__row clearfix">
            <label class="form__label">@Html.Localize("Profile.FirstName.lbl")</label>
            @Html.TextBoxFor(m => m.BasicModelData.FirstName, new { @class = "form__input", @placeholder = Html.Localize("Profile.FirstName.Placeholder"), data_val_required = "Debes de ingresar tu nombre", data_val = "true" })
            @Html.ValidationMessageFor(m => m.BasicModelData.FirstName)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">@Html.Localize("Profile.LastName.lbl")</label>
            @Html.TextBoxFor(m => m.BasicModelData.LastName, new { @class = "form__input", @placeholder = Html.Localize("Profile.LastName.Placeholder"), data_val_required = "Debes de ingresar tu apellido", data_val = "true" })
            @Html.ValidationMessageFor(m => m.BasicModelData.LastName)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Correo Electrónico</label>
            @Html.TextBoxFor(model => model.CorreoElectronico, new { @class = "form__input", id = "Email", name = "Email", @placeholder = "Email", @readonly = "true", type = "email" })
            @Html.ValidationMessageFor(model => model.CorreoElectronico)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Universidad</label>
            <div>
                @Html.DropDownListFor(model => model.Universidad, Model.Universidades, new { name = "university", @class = "js-universities-select select2-hidden-accessible", placeholder = "Selecciona una Universidad", id = "university" })
            </div>
            @Html.ValidationMessageFor(model => model.Universidad)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Profesión</label>
            @Html.TextBoxFor(model => model.Profesion, new { @class = "form__input", @placeholder = "Profesión", type = "text", id = "Profession", name = "Profession" })
            @Html.ValidationMessageFor(model => model.Profesion)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Celular</label>
            @Html.TextBoxFor(model => model.Celular, new { @class = "form__input", @placeholder = "Celular", type = "number", id = "phone", name = "phone" })
            @Html.ValidationMessageFor(model => model.Celular)
        </div>
        <div class="form__row clearfix">
            @Html.Action("TagPicker", "UserTags", new { entityId = Model.BasicModelData.Id })
        </div>
        <div class="form__row clearfix">
            <label class="form__label">País</label>
            <div>
                @Html.DropDownListFor(model => model.Pais, Model.Paises, new { name = "countryId", @class = "form__input js-select-field", placeholder = "Selecciona un País", id = "countryId" })
            </div>
            @Html.ValidationMessageFor(model => model.Pais)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Ciudad</label>
            <div>
                @Html.TextBoxFor(model => model.Ciudad, new { @class = "form__input", @placeholder = "Ciudad", data_val = "true", id = "cityId", name = "cityId" })
            </div>
            @Html.ValidationMessageFor(model => model.Ciudad)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Fecha de Nacimiento</label>
            @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form__input", @placeholder = "Fecha de nacimiento", data_val = "true", id = "birthdate", name = "birthdate", type = "text", @readonly = true })
            @Html.ValidationMessageFor(model => model.FechaNacimiento)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Nueva Contraseña</label>
            @Html.PasswordFor(model => model.NuevaContraseña, new { @class = "form__input", @placeholder = "Nueva Contraseña", data_val = "true", id = "password", name = "password" })
            @Html.ValidationMessageFor(model => model.NuevaContraseña)
        </div>
        <div class="form__row clearfix">
            <label class="form__label">Confirmar Nueva Contraseña</label>
            @Html.PasswordFor(model => model.ConfirmarContraseña, new { @class = "form__input", @placeholder = "Confirmar Contraseña", data_val = "true", id = "confirmPassword", name = "confirmPassword" })
            @Html.ValidationMessageFor(model => model.ConfirmarContraseña)
        </div>
        <div class="form__row clearfix">
            <div class="check">
                <label class="check__label">
                    @Html.CheckBox("js-member-notifier-setting",
                               Model.BasicModelData.MemberNotifierSettings[NotifierTypeEnum.EmailNotifier],
                               new
                               {
                                   notifiertype = NotifierTypeEnum.EmailNotifier,
                                   @class = "check__box",
                                   dataConfirmMessage = @Html.Localize("Profile.NotifierSettings.Confirmation.lbl")
                               })
                    <label class="form__label">@Html.Localize("Profile.EmailNotifications.Title.lbl")</label>
                    <span class="check__fake-input icon-check"></span>
                    <span class="check__fake-label">@Html.Localize("Profile.EmailNotifications.lbl")</span>
                </label>
            </div>
        </div>
        <div class="form__row--no-indent clearfix">
            <input type="hidden" name="mediaRootId" value="@Model.BasicModelData.MediaRootId" />
            <input class="btn _submit" type="submit" value="@Html.Localize("Profile.Save.btn")" />
        </div>
        @Html.ValidationSummary()
    }

</div>`

**Comment by MiguelIPerez** [comment]
I closed this issue by mistake, and reopened another exacctly like this
