### ISSUE TITLE
How to extend Edit Profile view 

### ISSUE THREAD

**Issue by MiguelIPerez** [Uintra/Uintra#24]
I am developing some web site using uintra as a template, and, i get a new requirement that says that i have to redesign the edit view from what uintra has to something more detailed.

- Photo
- First Name
- Last Name
- College
- Carreer
- Tags

and so on...
I did know how to do it properly, so, I created pretty much everything from scratch, and, replaced the default uintra's Edit view to my own, but i am having a problem; I am unable to edit the picture, everytime i click save, the MediaRoot, Photo and NewMedia, are null in the model every other data is there, except those properties, and i dont know how to pass it to the controller, do you have a how to about extending the edition view in order to fullfil the requirement?.

**Comment by denprodan** [comment]
Hi @MiguelIPerez. Could you please post your custom view, view model and control action. And we will try to figure out how to make it work:)

**Comment by UintraContact** [comment]
Hi @MiguelIPerez we consider this task as a closed, since we do not have your input here for more than 14 days, we hope you managed it and it works for you now. else, just reopen / add new issue
