### ISSUE TITLE
Would like some pages to be open to everyone

### ISSUE THREAD

**Issue by VidarM** [Uintra/Uintra#25]
Hi
I am trying to open some pages to anonymous. 

Where in UIntra is the "lock" defining that all pages should be protected? 

I tried to change  web.config 
`<authorization>
  <allow users="*" />
</authorization>`

I do not know where to look, if someone could point me in the right direction, it would be great.

Cheers
Vidar

**Comment by VidarM** [comment]
Great! Then I will wayt for this version :-)

**Comment by mabjaiacode** [comment]
> Hi Vidar
> In current implementation member has to be logged in to see intranet pages
> In 1.3 release we are going to implement member roles manegement feature. As part of feature there will be anonymous access to contetnt pages

HI all, have this feature been implemented?

**Comment by denprodan** [comment]
Hi @mabjaiacode 
We have implemented this feature in separated branch for Uintra 2.0
It's finished but not tested well. When we finish testing and fixing bug it will be merged to release branch
Take a look at features/anonymous-pages

**Comment by mabjaiacode** [comment]
Thanks for the feedback. Can you provide the link for features/anonymous-pages, i couldn't find it

**Comment by denprodan** [comment]
@mabjaiacode  https://github.com/Uintra/Uintra/tree/features/anonymous-pages
