### ISSUE TITLE
Upgrading Uintra

### ISSUE THREAD

**Issue by ChrisAngel447** [Uintra/Uintra#26]
Good morning Team,

I see that there is an update of Uintra of version 1.1.0. I am currently running Version 1.0.0.1.

Now to update Umbraco via the files I know how to do but is there a prefered way you can recommend updating Uintra without losing all the work that has already been done?

Kind regards 

Chris

**Comment by denprodan** [comment]
Hi @ChrisAngel447. 
You mean you custom code, views and logic?

**Comment by ChrisAngel447** [comment]
Hi Denis

I mean the database and all the media that has been uploaded. So just to upgrade to version 1.1.0 without having the need to redeploy. As in copy files over and replace.

**Comment by denprodan** [comment]
In every release we support migration, so if something changed in database or in Umbraco content appropriate migration will be applyed, so don't worry about that.(Migrations are store in __MigrationHistory and uIntra_MigrationHistory tables)
P.S. But good approach to have backups of source and database before every deploy for quick rollback if something gone wrong

**Comment by ChrisAngel447** [comment]
That is perfect. Can you advise on what files I need to copy over to upgrade Uintra?

**Comment by denprodan** [comment]
There are two options to update Uintra:
1. Via Nuget. Use Nuget Package Manager 
![image](https://user-images.githubusercontent.com/25720118/52112556-8341c000-260f-11e9-8d27-53bd6d512f42.png)

2. Via Umbraco package
https://our.umbraco.com/packages/collaboration/uintra/

**Comment by ChrisAngel447** [comment]
Hi Denis 

Ahhh yes, The package one would be the best way for us to keep it up to date. 

I would then be using the developer tab in the menu and use the install local option to upload the package. Is that correct?

**Comment by denprodan** [comment]
Hi @ChrisAngel447. Yes, it is

**Comment by ChrisAngel447** [comment]
Hi Denis 

One last question regarding this. When I installed Uintra on Umbraco I went the NuGet package route.

I just went to developer tab and under Installed packages, I see that it is empty and not showing Uintra, would that be a problem when using the package to upgrade?

**Comment by denprodan** [comment]
Frankly saying we didn't try to update Uintra in different way that it was installed at first time. As I am right understood  you installed it via Nuget before?

**Comment by ChrisAngel447** [comment]
That is correct. I installed Uintra on Umbraco using NuGet.

**Comment by ChrisAngel447** [comment]
In the meantime, I will install Umbraco via NuGet packages and install Uintra manually using the package. 

The upgrading method via the package will work great in our environment.

**Comment by cdecinkoKnight** [comment]
Something I tripped on in my test upgrade, I wiped out some of my customizations.

**Comment by UintraContact** [comment]
Hi @ChrisAngel447 , based on your latest comment, we consider this task as resolved and close it. please, add new issue, if you still have some problems with Uintra ;)
