### ISSUE TITLE
Elasticsearch as a service

### ISSUE THREAD

**Issue by lautarobonetto** [Uintra/Uintra#27]
Hi.
This is not an issue. It's more like a question.
We want to use a SaaS service of Elasticsearch. This kind of services has basic login security as a minimum. Is there a way on uIntra to specify a user and password to connect to an Elasticserach URL? 
We want to use https://www.elastic.co/cloud/elasticsearch-service

Thanks

**Comment by denprodan** [comment]
Hi @lautarobonetto 
Could you please post error stacktraces?

**Comment by lautarobonetto** [comment]
This is not an issue. I have no error stacktraces to share with you.
This is a question.

**Comment by UintraContact** [comment]
hi @lautarobonetto thanks for that issue, we will do Uintra more flexible in that elastic setup context and announce this change in one of our future releases, just follow us here https://uintra.com/releases/  and thanks again for that good point
