### ISSUE TITLE
Elasticsearch version

### ISSUE THREAD

**Issue by lautarobonetto** [Uintra/Uintra#28]
Hi.
Currently, the SaaS service of Elasticsearch Service allows me to deploy the version 5.6.14.
Is it compatible with uIntra?

Thanks.

**Comment by denprodan** [comment]
Hi @lautarobonetto. Unfortunately now Uintra works only on 5.2.1. We can't garantee thats search will work correct on other elasticsearch versions
But you can install version you need and fix issues releted with this update
and make pull request in Uintra repo:)

**Comment by UintraContact** [comment]
Hi @lautarobonetto we have added this upgrade to internal tasks system, for one of next releases. this issues will be closed for now, and we will announce this upgrade, when it is done.

add new issue, please, if you have errors related with current version
