### ISSUE TITLE
Default Event Publish Date

### ISSUE THREAD

**Issue by juganrising** [Uintra/Uintra#34]
When I create an event and leave the Event start date and time as the default value and save the event it doesn't appear under the events, but if I select today's date for the Event publish date and time then it changes the date time from 12.02.2019 11:41 to 12.02.2019 00:41 and then it will show up under the Events.

**Comment by juganrising** [comment]
Also if we set the publish date to 10 minutes in the future we don't see the event show up even an hour after the event should have been published e.g. 12.02.2019 11:41 to 12.02.2019 11:51.

**Comment by denprodan** [comment]
Hi @juganrising. 
Thanks, we created appropriate task in our internal system. Will fix it in the next Uintra release
