### ISSUE TITLE
Event Sorting

### ISSUE THREAD

**Issue by juganrising** [Uintra/Uintra#35]
When I look at the events it seems that they are just listed by the date they were publish ascending. 
![image](https://user-images.githubusercontent.com/39747824/52660139-418d0100-2ebc-11e9-80a3-eb6c3b7f6193.png)

Shouldn't they be ordered by the Event Start date?

**Comment by denprodan** [comment]
Hi @juganrising. Correct in current implementation events sorting by Published Date
But if you need another kind of sorting for event you can write your own implementation of IFeedItemService.IEnumerable<IFeedItem> GetItems(); for EventsService

**Comment by juganrising** [comment]
I see it as a feed that shows the next upcoming events which is why I think it should be sorted by event date so that people can see the events in order.

Perhaps we are using the events incorrectly, would you be able to describe how they are supposed to be used? 

Lets say for example I want to enter all the statutory holidays each year on January 1st of every year, how would I set those up so they appear correctly in the events so that people are aware that they are coming up and will be visible at least a week in advance?

**Comment by denprodan** [comment]
1. For now you have to create Event for each date (f.e. New Year 2018 party and New Year 2019) You can't create one event which be repeated in every year. But it's a good point, we will discuss this with team
2. All upcoming events you could see in Coming events panel
![image](https://user-images.githubusercontent.com/25720118/52799512-a3976300-3082-11e9-9d1a-76a8a4056749.png)
Also Uintra contain reminder functionality and all members who subscribed to this event will be notified 24 hours before the event

**Comment by juganrising** [comment]
So the feed is just for the latest published items, and then we should be using panels to show the information in the correct order.
