### ISSUE TITLE
News items showing before publish date

### ISSUE THREAD

**Issue by juganrising** [Uintra/Uintra#36]
When you publish a News item with a future date for a publish date it shows up in the feed right away. Others can't see it (until it is published I am guessing) but it is a little misleading for the author since there is nothing to indicate that it's not actually published yet.

![image](https://user-images.githubusercontent.com/39747824/52665539-178e0b80-2ec9-11e9-87d7-d8edd13e977e.png)

When I inspect the source there is actually a tag there that says Inactive but it's being hidden.

![image](https://user-images.githubusercontent.com/39747824/52665633-486e4080-2ec9-11e9-9d1f-db8e90d9246b.png)

**Comment by juganrising** [comment]
Digging into it a little deeper, all the news and event items have Inactive on them but may not be used. News items show when they are future dated but events don't. It would be nice to be consistent and have some visual cue to indicate that they are not visible to everyone yet.

**Comment by denprodan** [comment]
Hi @juganrising 
[Inactive] it's not for News or activity at all
[Inactive] label appears only when member who created this news was deleted or inactivated in system

**Comment by juganrising** [comment]
That's good to know. Is there no identifier so that the person who published the news item can safely tell that their news item hasn't been published yet?

This functionality is also different than how Events behave, if you create a Event where the publish date is in the future then the only way to see it is by going into the backoffice.

**Comment by denprodan** [comment]
Uintra hasn't functionality like that
That's the point of Publish Date. It's deferred publish

**Comment by juganrising** [comment]
Okay thanks, it's just an understanding thing for your software. 

So the feeds are always based on published date where future dated items are not visible to others until the specified date/time.
