### ISSUE TITLE
Content panel email link

### ISSUE THREAD

**Issue by juganrising** [Uintra/Uintra#37]
When you insert a link in the RTE in a content panel using the Email option and you enter something other than the auto generated title it will Base64 encode the highlighted text.
![image](https://user-images.githubusercontent.com/39747824/52817855-61f6c000-3062-11e9-870c-f52db52d95ef.png)

It also does not pull the values back into the link picker when you try to edit the email link.
![image](https://user-images.githubusercontent.com/39747824/52817748-088e9100-3062-11e9-81c0-81cda4a72279.png)

I tried to add the remove link to the RTE but it doesn't seem to be one of the ones under Data Types, is this through one of your custom plugins?

**Comment by denprodan** [comment]
Hi @juganrising. Thanks. We create appropriate task in our internal system. This issue will be fixed in next Uintra release
