### ISSUE TITLE
Group Members throws a 404

### ISSUE THREAD

**Issue by juganrising** [Uintra/Uintra#38]
When I try to access the members in a group I get the default 404 error. I tried to look in the Umbraco logs and in the event logs but there is no error recorded. If you can tell me how to get more details for the error then I will post it. 

![image](https://user-images.githubusercontent.com/39747824/52825762-4d72f180-307b-11e9-8b51-2d1eb5421037.png)

**Comment by denprodan** [comment]
Hi @juganrising. 
It looks like there is no group with such id or this group was deactivated from backoffice

**Comment by juganrising** [comment]
Hi @denprodan, even when I create a brand new group and go to the Group members it sends me to the 404 page. This same functionality happens when you try and view the group members on the demo site as well.

https://demo.uintra.com/groups/room/group-members?groupId=c466331f-6786-44cc-ab94-222e3e01efbd

**Comment by denprodan** [comment]
Hi @juganrising.
We fixed it on demo
We had a bug in transformations
Please change elasticsearch service url in web config to http://40.89.185.254:49200/
![image](https://user-images.githubusercontent.com/25720118/53089754-205c8e00-3516-11e9-9759-ccd053413ef4.png)
Also don't forget do rebuild index from backoffice
![image](https://user-images.githubusercontent.com/25720118/53089825-4b46e200-3516-11e9-822f-e8acd2560b91.png)
Looking forward for feedback

**Comment by juganrising** [comment]
I will get back to you on this, we are downgrading our elasticsearch to 5.2.1.

**Comment by juganrising** [comment]
Yes it is working now. We downgraded our elastic search to 5.4.

**Comment by UintraContact** [comment]
> Yes it is working now. We downgraded our elastic search to 5.4.

sounds great, thanks for update @juganrising
