### ISSUE TITLE
Date Time Localization

### ISSUE THREAD

**Issue by juganrising** [Uintra/Uintra#39]
I see everything is currently set to UTC+0. I was looking through the localization section in the backend and I didn't see anything for date/time localization.

Is there a way to set a timezone in the system?

**Comment by denprodan** [comment]
Hi @juganrising. Yes now all time on the server sets to UTC.
Timezone sets automatically due to client locations

**Comment by juganrising** [comment]
Ah I see, last week everything was showing as UTC time on the front end but now it's showing in the correct timezone. Not sure if it's because the server rebooted over the weekend or not.
