### ISSUE TITLE
Group documents

### ISSUE THREAD

**Issue by ChrisAngel447** [Uintra/Uintra#4]
Hi guys, 

this ticket isn't really an issue but more of a check, unless you see it as an issue.
I have created multiple groups on the site. And for testing purposes, I created a text file with the group name as the name of the file. I went to each group and uploaded each file to the appropriate group. 
I then log into Umbraco back office and go to the media tab under the groups content folder. 
Here I only see 1 folder of the groups that I created but all the files in it. 
I was under the impression that it would create a folder for each group that I have created.
Do I have to create the Folders manually for it to save in them or should it be like automatic like the one folder that was created but for all?

Kind regards and thanks 

Chris

**Comment by KasperUintra** [comment]
As Denis explained it is working as intended, BUT we are looking to change this so the files are separated in different folders the backlog, for now we have a couple of big features prioritized above this in the pipeline for our next release, so it will most likely first be developed for the following release!

If you are interested in diving into this yourself and need some additional information, let me know!

Best regards,
Kasper

**Comment by ChrisAngel447** [comment]
Hi Kasper 
I would love to dive into this. 
Kind regards and thanks 
Chris

**Comment by KasperUintra** [comment]
Awesome! I'll be back with some pointers to how it can be done
