### ISSUE TITLE
how to embed external content

### ISSUE THREAD

**Issue by JdevJ** [Uintra/Uintra#40]
Need to embed the following content ? :

<script src="https://ats.dittojobs.com/iframe/get/407476218"></script>

**Comment by denprodan** [comment]
Hi @JdevJ. Where you need to embed that script?

**Comment by JdevJ** [comment]
Hi @denprodan, A Intranet user wants to embed this into a Content Panel. so that external content is loaded, 
Add the following to a html file and open:
<script src="https://ats.dittojobs.com/iframe/get/407476218"></script>

**Comment by denprodan** [comment]
In current implementation it's not allowed to embed whatever in Content Panel
But if you need to:
1. go to App_Plugins\Panels\package.manifest
2. Find Content Panel in json and add Code toolbar
![image](https://user-images.githubusercontent.com/25720118/53005820-ac01ec00-343c-11e9-8a15-a71afb5e1386.png)
3. Rebuild soultion
And after that on Content Panel you would be able to edit source code of tiny-mce control
![image](https://user-images.githubusercontent.com/25720118/53005906-dce22100-343c-11e9-9a82-f9416a28d8fd.png)
![image](https://user-images.githubusercontent.com/25720118/53005937-f08d8780-343c-11e9-81fa-08e95accb229.png)
Here You can embed whatever you need to

**Comment by JdevJ** [comment]
thank you @denprodan, I can certainly understand why not allowed. Thank you for the assistance.

**Comment by JdevJ** [comment]
Hi @denprodan, 
I've done as suggested but when inserting the code and after clicking OK nothing happens and it dissapears. 
![image](https://user-images.githubusercontent.com/47749043/53014894-7b2cb180-3452-11e9-8062-8f398a98b182.png)

**Comment by JdevJ** [comment]
@denprodan , I also attempted altering the tinyMceConfig.config with : 
_extended_valid_elements : "script[type|src|language|async|defer|charset]"_

**Comment by JdevJ** [comment]
*bumb

**Comment by denprodan** [comment]
Hi @JdevJ 
What this script supposed to do?

**Comment by JdevJ** [comment]
Hi @denprodan, This script loads available vacancies, jobs, from an employment portal.

Add the following to a html file and open the newly created html file:
<script src="https://ats.dittojobs.com/iframe/get/407476218"></script>

**Comment by denprodan** [comment]
Hmm.. Not sure that tiny-mce control will allow to do that because of security
If you need to show some data from external source the better way is doing it from backend.
Write your own panel and load data in there
But it's a lot of work to do
If you need a could write you a manual how to do it

**Comment by JdevJ** [comment]
@denprodan Yes please, this will certainly help.

**Comment by JdevJ** [comment]
Hi @denprodan , please let me know about the manual or if you can point me in another diretion.

thanks !

**Comment by denprodan** [comment]
Hi @JdevJ
Sorry for delaying. We have wrote this manual. And now we are adding it to the Uintra docs. I will write you back soon

**Comment by JdevJ** [comment]
Thank you @denprodan , You guys are awesome.

**Comment by UintraContact** [comment]
hi @JdevJ  you can see it even before we publish it in docs, just look and let us know, if something still not clear or not working 
[Uintra - How to create custom panel.docx](https://github.com/Uintra/Uintra/files/2951235/Uintra.-.How.to.create.custom.panel.docx)
