### ISSUE TITLE
Shared Links Block not as expected

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#41]
The Shared Links section is showing two items for each link, the group title and the link.  How is this section supposed to display?

![image](https://user-images.githubusercontent.com/46462212/53117445-2a779000-3508-11e9-8bc7-2756dd2503fa.png)

**Comment by denprodan** [comment]
Hi @cdecinkoKnight 
Our QA can't reproduce that issue
Could you share steps how to get it?

**Comment by cdecinkoKnight** [comment]
The example I show is:
Links Group Title
Name
Links Group Title
Name

What is the purpose of the Links Group Title if not for grouping?

**Comment by denprodan** [comment]
Now it's fixed
Please let us know if it does not work for you
