### ISSUE TITLE
Empty panels should be hidden or show that there is no content

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#42]
Content panels with no associated content are showing as empty containers:

![image](https://user-images.githubusercontent.com/46462212/53127312-666a1f80-351f-11e9-8054-58570f946383.png)

They should hide or display a message that there is no content.

**Comment by cdecinkoKnight** [comment]
This is happening when a document list is not linked to a media folder.

**Comment by denprodan** [comment]
Hi @cdecinkoKnight 
Will fix that in v1.3
