### ISSUE TITLE
Customization of Notification emails to not display UIntra

### ISSUE THREAD

**Issue by JdevJ** [Uintra/Uintra#44]
Need the ability to customize notification emails to not display UIntra, but rather use display name in Smtp settings.

**Comment by denprodan** [comment]
Hi @JdevJ 
There 2 keys in Web.config.AppSettings
![image](https://user-images.githubusercontent.com/25720118/53245862-afed7280-36b7-11e9-9c82-20d0f71f1864.png)

**Comment by JdevJ** [comment]
awesome thanks
