### ISSUE TITLE
Elastics isn't indexing content

### ISSUE THREAD

**Issue by lautarobonetto** [Uintra/Uintra#46]
Hi.
I have an uIntra instance here: http://18.214.44.62
On the infrastructure, we have 3 VMs. One for the SQL, other for the IIS and the last one for Elasticsearch.
The website looks to work well, but we realized it isn't indexing the new content. In fact, it indexed just users.
What is wrong? Those issue isn't happening in Test and Dev environment. Those envs are quite different, the code is exactly the same one.
Looks like there is a restriction between IIS and elasticsearch, but we have no idea how to fix it.

Thanks!!

**Comment by denprodan** [comment]
Hi @lautarobonetto.
Hm. It's strange. I guess if it is a problem with some restrictions, users also wasn't indexing
I suggest you to add logs to IElasticSearchRepository and look what happens when entity comes mb some errors from elastic or entity not coming to index

**Comment by cdecinkoKnight** [comment]
I've forced my search collections to rebuild yet nothing ever comes up in search results.

**Comment by denprodan** [comment]
@cdecinkoKnight Please let us know if after install Elasticsearch the index doesn't work
Related issue: https://github.com/Uintra/Uintra/issues/52
