### ISSUE TITLE
Force comments/postings to be moderated

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#49]
**Is your feature request related to a problem? Please describe.**
Potential for some users to abuse comments or clutter with no value comments.

**Describe the solution you'd like**
Make comments be unpublished by default. Provide easy way for someone other than admin to approve/publish comments.

**Describe alternatives you've considered**

**Additional context**

**Comment by UintraContact** [comment]
hi @cdecinkoKnight as Uintra more targeted for now for users with part of responsibility, for their posts, we did not implemented it. but yes, it is in our pipeline for future. thanks
