### ISSUE TITLE
Error webpack.optimize.CommonsChunkPlugin

### ISSUE THREAD

**Issue by danielcalvete19** [Uintra/Uintra#5]
Hello guys

When I am trying to compile npm run watch, I got an error with the webpack.config file that says

webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.

do you know what is the correct configuration for new versions of webpack?

**Comment by ChrisAngel447** [comment]
Hi Daniel,

I'm another Unitra user. Would it maybe help if I share my `webpack.config.js` with you?

Regards Chris

**Comment by danielcalvete19** [comment]
Hi Chris

Yes please, it would be perfect, but how would you share the webpack.config.js file with me?

maybe with a comment here?
or with this website https://pastebin.com/? 

I would appreciate it very much

**Comment by ChrisAngel447** [comment]
Good morning Daniel

I have share the code on pastebin, follow the link bellow:

https://pastebin.com/Adp3MEVJ

I hope this helps!

Kind regads and thanks 
Chris

**Comment by DenysDzhel** [comment]
Hi Daniel

As I understood you are trying to use webpack v4, according to this you need to do at least following changes:

1. Remove  
`new webpack.optimize.CommonsChunkPlugin({
                names: ['app', 'vendors'],
                minChunks: Infinity
            }),`
CommonsChunkPlugin was removed and Webpack 4 now by default does such optimizations automatically.

2. same as 1 `new webpack.NoEmitOnErrorsPlugin(),`

3. Use 'mini-css-extract-plugin' instead of 'text-extract-plugin'

**Comment by danielcalvete19** [comment]
Hi Denys, 

thanks for your help, I applied your tips, but I still have errors running the command "npm run watch".

the actual configuration of webpack.config.js doesn´t work fine with the webpack v4 for me.

this is my current webpack file configuration:

https://pastebin.com/vp1W1szd

**Comment by DenysDzhel** [comment]
Hi Daniel

Could you also attach your package.json ? I will try do my best

**Comment by danielcalvete19** [comment]
I had to reuse the initial configuration of the package.json, the problem is with wepack 4.
