### ISSUE TITLE
Provide a way to test SMTP settings

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#50]
**Is your feature request related to a problem? Please describe.**
Only way to test the SMTP settings is to perform an action that sends mail.

**Describe the solution you'd like**
Add a button to the SMTP settings page that sends a test email to confirm that the settings are correct.

**Describe alternatives you've considered**

**Additional context**

**Comment by vmatsukatov** [comment]
hi @cdecinkoKnight  aplogize for the very late answer, all that points will be considered and added to the new documentation for Uintra we will start working on just we release Uintra 2.0 based on Umbraco 8, we are in fulls peed and efforts there now
