### ISSUE TITLE
Translation is not working as expected

### ISSUE THREAD

**Issue by manylson** [Uintra/Uintra#51]
Hello, I am currently dedicated to creating an intranet project using this framework, and I certainly hope to collaborate with the project within my limitations (I am a front-end developer).

In this first week of work with uIntra, I came across the following situation:

**The bug**
Apparently when the project renders any "view" that comes from the App_plugins folder (and subfolders), the configured translation is ignored and the default language "en"/"en-US" seems to be the reference again.

**To Reproduce**
1) Set up a new language for the whole website (and make the necessary settings like: "Culture and Hostnames" / backoffice, umbracoDefaultUILanguage / web.config and "Language" in the user profile).
2) Translate the terms of pages referring to the creation / editing of an event (As an example: Pin.SetPinned.lbl, SubscribeSettings.CanSubscribe.lbl) in the backoffice.
3) On the page, the term "SubscribeSettings.CanSubscribe.lbl" always maintains the language in English.
(Screenshots below)

**Expected behavior**
Localization settings working for the whole website.

**Screenshots**
Image 1
![screenshot_1](https://user-images.githubusercontent.com/12956133/54954055-7dd66700-4f28-11e9-91cc-1bf42a852b38.png)
Image 2 (Result - Portuguese on the first label)
![image](https://user-images.githubusercontent.com/12956133/54954126-aa8a7e80-4f28-11e9-8257-3328c8a311a5.png)
Image 3
![screenshot_2](https://user-images.githubusercontent.com/12956133/54954843-6bf5c380-4f2a-11e9-856e-a8c5fbeb7e61.png)
Image 4 (Result)
![image](https://user-images.githubusercontent.com/12956133/54954275-06550780-4f29-11e9-8f58-c4ac3ba93eb3.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 73

**Comment by denprodan** [comment]
Hi @manylson.
Unfortunately Uintra not multilingual
But as I am right understood some labels were translated to another language somehow?
Anyway we give this issue to our QA
And I will back to you ASAP

**Comment by manylson** [comment]
@denprodan Thanks for the reply. At first I will only use 1 language in my intranet project, but I have tried the correct way to keep the English texts unchanged (and create my own).

There are several places where the two languages are mixing, including in the feed itself. In the future I'll be posting more evidence, if necessary.

**Comment by denprodan** [comment]
It would be very helpfully for us if you will show some views where transltations to other language work correct

**Comment by mabjaiacode** [comment]
Greetings to all. Has the language variation feature been added?

**Comment by mabjaiacode** [comment]
@manylson , Have you found a way to create  language variation?
