### ISSUE TITLE
Is it necessary to install Elasticsearch?

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#52]
Is it necessary to install Elasticsearch after setting up Uintra or is the search supposed to be built in? I don't see any reference in the install instructions other than if search does not work, go to this link.

**Comment by denprodan** [comment]
Hi @cdecinkoKnight 
Yes, it is necessary to install Elasticsearch
We are currently update manual with this section
If you don't want to wait please use this https://www.elastic.co/guide/en/elasticsearch/reference/5.2/setup.html, 
hope it will help you to instal Elasticsearch
Please be sure that you install 5.2.1. 
Only on this version we can garantee correct work of Uintra search
P.S. Also here the issue which already closed where you can find some solutions if you will have questions on Uintra search 
https://github.com/Uintra/Uintra/issues/19
