### ISSUE TITLE
Small Issue - Key impossible to translate 

### ISSUE THREAD

**Issue by manylson** [Uintra/Uintra#53]
Hi, in my translation process, I face the following key which is impossible to translate. Obviously the text seems well out of context

![image](https://user-images.githubusercontent.com/12956133/55186861-5543ac80-5176-11e9-95c3-e48a71c4da30.png)

![image](https://user-images.githubusercontent.com/12956133/55186802-2e857600-5176-11e9-9152-1c7ec4c70277.png)

https://github.com/Uintra/Uintra/blob/7f29a75e48cc2960cbd91b1575a7312209c66b86/src/Compent.uIntra/Core/Updater/Migrations/0.0.0.1/PreValues/DefaultLocalizations.json#L453

**Comment by denprodan** [comment]
Hi @manylson 
Your key not valid because key format is #Key.To.Translate.lbl# (key in brackets)
If you want to paste translation in the middle of the text you could write something f.e. like that:

> <p>My very usefull @Html.Localize("Key.To.Translate") text</p>

**Comment by manylson** [comment]
Ok. I will create my own key to replace this translation.

But the key mentioned in the topic is in the official project, I did not create it.

Branch 1.3:
https://github.com/Uintra/Uintra/blob/7f29a75e48cc2960cbd91b1575a7312209c66b86/src/Compent.uIntra/Core/Updater/Migrations/0.0.0.1/PreValues/DefaultLocalizations.json#L453

**Comment by denprodan** [comment]
Oh. That's true, our bug
We will change it in 1.3 version
Also I've noticed that you mentioned 1.3 branch
We recommend to use code from branch that already launched, it's 1.2 for now
Cause in 1.3 there is active development now

**Comment by manylson** [comment]
Thank you. All right, I'll do it in the next posts.
