### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by SimonAntony** [Uintra/Uintra#55]
**Describe the bug**
Installed unitra to a new web project, 4.7.1 framework, latest version via Nuget
Once installed, I do a build and get an error building complaining that the task library is invalid and this results in a failed build. 

**To Reproduce**
Install Unitra as per instructions with VS2017, do a build and error shows

**Expected behavior**
Should build with no errors ;-)

**Screenshots**

**Desktop (please complete the following information):**
Windows 10, VS 2017 Pro, SQL Server 2017 (although not got this far yet!)

**Comment by denprodan** [comment]
Hi. Could you please share what kind or errors you get when building project
