### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by JdevJ** [Uintra/Uintra#56]
Dear Uintra, 

Is it possible to control the user timeout and prolong or disable this logging into Intranet frontend?

**Comment by denprodan** [comment]
Hi @JdevJ. Sorry for the late answer. Is it still topical for you?
You could override LoginController => Login method and add logic which you need

**Comment by JdevJ** [comment]
No Problem, yes it is still on the table.

**Comment by denprodan** [comment]
Hi @JdevJ  Did you figure out how to override LoginController => Login. Do you need help?

**Comment by JdevJ** [comment]
Would appreciate some assistance, My web Developer is out of the office currently
