### ISSUE TITLE
Is there a way to make the feed open to everyone?

### ISSUE THREAD

**Issue by MiguelIPerez** [Uintra/Uintra#57]
** i would like to open the news feed to everyone
I would like to make the news feed anonymous so everyone can see the content of the web page without the need to login.

** But, if the anonymous user want to interact it should be redirected to the login page.

is related to this https://github.com/Uintra/Uintra/issues/25 

but what is the status of this feature.

Thank you

**Comment by UintraContact** [comment]
Hi @MiguelIPerez thanks for your issue. this feature is one of the first in our pipeline for new Uintra based on Umbraco 8 version. which is unfortunately not something you can expect next 3 month :(.

in current implementation, you can do it yourself, by setting member roles in Uintra for umbraco items. + yes, additiona development here, to add logic for interaction and redirect. 

else, you can contact us here https://uintra.com/contact/ if you need a price for that customization for your Uintra installation as customization (not part as existing Uintra baseline)

**Comment by MiguelIPerez** [comment]
humm is there some documentation on how can i use this role management to make my content accessible??

**Comment by MiguelIPerez** [comment]
nvm I found it

**Comment by MiguelIPerez** [comment]
is this the roles you are talking about https://docs.uintra.com/getting-started/roles-permissions/v1.3.0/
