### ISSUE TITLE
How to enter connection string

### ISSUE THREAD

**Issue by marcoeab** [Uintra/Uintra#58]
Hello, I am stuck in step 6.2 of the Uintra on Azure installation guide. When I enter the connection string, I keep getting the message "Could not connect to database". Can you please help me and advise how the connection string must be entered? This is the one coming from Azure: Server=tcp:eabserver.database.windows.net,1433;Initial Catalog=EABintraDB;Persist Security Info=False;User ID={your_username};Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; Even after replacing username and password with the correct values, I keep getting the error. Thanks! Marco

**Comment by denprodan** [comment]
Hello there @marcoeab. Did you try to connect to your database via SSMS or other tool?
Looks like db is closed for external connections

**Comment by marcoeab** [comment]
Hi Denis, my database is on Azure. I did set the Firewall settings there, to make sure that all IP addresses can pass.

 

Thanks for your help!

Marco

 

Van: Denis Prodan <notifications@github.com> 
Verzonden: woensdag 9 oktober 2019 6:40
Aan: Uintra/Uintra <Uintra@noreply.github.com>
CC: marcoeab <marco.doorakkers@eenanderbedrijf.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Uintra/Uintra] How to enter connection string (#58)

 

Hello there @marcoeab <https://github.com/marcoeab> . Did you try to connect to your database via SSMS or other tool?
Looks like db is closed for external connections

**Comment by denprodan** [comment]
So did you try to connect to your database from your local environment via some tool like SSMS?

**Comment by marcoeab** [comment]
Yes – I did now. I get an error from here as well (see below). I probably miss something there. Are you able to see what I miss from the text below?

 

And how should the connection string look like when I manage to solve this? Must the provider part be included?

 

Thanks, Marco

 

===================================

 

Cannot connect to eabserver.database.windows.net.

 

===================================

 

One or more errors occurred. (mscorlib)

 

------------------------------

Program Location:

 

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)

   at System.Threading.Tasks.Task.Wait()

   at System.Data.SqlClient.SqlInternalConnectionTds.GetFedAuthToken(SqlFedAuthInfo fedAuthInfo)

   at System.Data.SqlClient.SqlInternalConnectionTds.OnFedAuthInfo(SqlFedAuthInfo fedAuthInfo)

   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)

   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject

 

Van: Denis Prodan <notifications@github.com> 
Verzonden: woensdag 9 oktober 2019 10:07
Aan: Uintra/Uintra <Uintra@noreply.github.com>
CC: marcoeab <marco.doorakkers@eenanderbedrijf.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Uintra/Uintra] How to enter connection string (#58)

 

So did you try to connect to your database from your local environment via some tool like SSMS?

**Comment by marcoeab** [comment]
I was able to connect from SSMS now! 😉

So I can connect from my local PC.

 

Van: Denis Prodan <notifications@github.com> 
Verzonden: woensdag 9 oktober 2019 10:07
Aan: Uintra/Uintra <Uintra@noreply.github.com>
CC: marcoeab <marco.doorakkers@eenanderbedrijf.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Uintra/Uintra] How to enter connection string (#58)

 

So did you try to connect to your database from your local environment via some tool like SSMS?

**Comment by marcoeab** [comment]
I also tried it via this way (see attached picture) – same result: Could not connect to database.

 

Thanks, Marco

 

Van: Marco Doorakkers | Een Ander Bedrijf <marco.doorakkers@eenanderbedrijf.nl> 
Verzonden: woensdag 9 oktober 2019 10:56
Aan: 'Uintra/Uintra' <reply@reply.github.com>; 'Uintra/Uintra' <Uintra@noreply.github.com>
CC: 'Mention' <mention@noreply.github.com>
Onderwerp: RE: [Uintra/Uintra] How to enter connection string (#58)

 

I was able to connect from SSMS now! 😉

So I can connect from my local PC.

 

Van: Denis Prodan <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: woensdag 9 oktober 2019 10:07
Aan: Uintra/Uintra <Uintra@noreply.github.com <mailto:Uintra@noreply.github.com> >
CC: marcoeab <marco.doorakkers@eenanderbedrijf.nl <mailto:marco.doorakkers@eenanderbedrijf.nl> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Onderwerp: Re: [Uintra/Uintra] How to enter connection string (#58)

 

So did you try to connect to your database from your local environment via some tool like SSMS?

**Comment by denprodan** [comment]
Can't see attached file. Could you please post it via Github site just in comment

**Comment by marcoeab** [comment]
![Connect the DB](https://user-images.githubusercontent.com/56300650/66505359-7ee97300-eacb-11e9-9d00-c7f9ea9423f3.png)

Hope is is visible now. Thanks, Marco
