### ISSUE TITLE
Email notifications not happening

### ISSUE THREAD

**Issue by ChrisAngel447** [Uintra/Uintra#6]
Hi Team, 

I'm having issues with the emails being sent out. I have added the SMTP settings for a mail address and when I run a test mail under settings tab it works. 

I have made sure that all notification types for mail are switched on but nothing is happening.
The Sent Emails and Outbox Emails only show the test mails but nothing else. 

Is there anything I can look into on why this is not happening?

Kind regards and thanks

Chris

**Comment by ChrisAngel447** [comment]
Hi Denis,

I do have a job section in the web.config.

Mine looked a bit different with regards to the ReminderJob like below:

`<add job="ReminderJob" enabled="true" runType="RunNow" />`

But otherwise its the same.

I have changed mine with yours but still no luck. Let me know if you want me to debug somewhere or need anything.

**Comment by denprodan** [comment]
Hi Chris. 
I am wondering how about in-app notifications, are they send to user?

**Comment by ChrisAngel447** [comment]
Hi Denis
The in-app notifications are working.

![image](https://user-images.githubusercontent.com/9823098/49138202-439ce600-f2f7-11e8-9565-353eda78e70c.png)

**Comment by denprodan** [comment]
![image](https://user-images.githubusercontent.com/25720118/49138834-f6ba0f00-f2f8-11e8-8ff5-99c5ddb57316.png)
Is sending email notifications enabled for user you tested?

**Comment by ChrisAngel447** [comment]
Hi Denis,
It was off and I have switched in on, However, after testing I see that the emails are sitting in the Outbox Emails folder. Sent Tries, Type ID, CC emails, Bcc Emails, From Emails and from Name are empty. 
I have also made sure that Is Test Mode is unticked.

Kind regards and thanks 

Chris

**Comment by denprodan** [comment]
Hi Chris. 
Looks like mail job from web.config doesn't run
Lets's run it manually 
Run this url from Postman or just go to it from your browser
GET http://{YOUR_URL}/umbraco/api/notificationJob/runMailJob

**Comment by ChrisAngel447** [comment]
I have gone through postman and did the above as mentioned but get a response back of nothing. Everything is empty.
![image](https://user-images.githubusercontent.com/9823098/49154243-963ec800-f320-11e8-94ea-afbc6e52068c.png)

**Comment by denprodan** [comment]
Yes, it has to be empty
But now all mails should be moved from Outbox to Sent Emails folder

**Comment by ChrisAngel447** [comment]
Good morning Denis,

I have left everything run for a while and still nothing. The tests mails go through but no mails to a person. Also made sure that all email addresses are correct.

Here a screenshot of how it looks like in my Outbox Email Folder:
![image](https://user-images.githubusercontent.com/9823098/49203546-5ffd5900-f3b1-11e8-919b-5b206718a386.png)

As you can see that some of the fields are left blank. Is this maybe the problem?

**Comment by denprodan** [comment]
Hi Chris.
I have created task in our internal system and come back to you with news ASAP

**Comment by ChrisAngel447** [comment]
Hi Denis,
Thank you very much!
Kind regards and thanks 
Chris

**Comment by denprodan** [comment]
Hi Chris
We have released patch for Uintra 1.0 where we fixed mail nitifications issue. 
https://www.nuget.org/packages/uIntra/1.0.0.1
Please update your project with this version
Looking forward for feedback from you

**Comment by ChrisAngel447** [comment]
Hi Denis,
I have upgraded, tested and can confirm that all is working as supposed to! 
Thank you very much!
Kind regards and thanks 
Chris

**Comment by denprodan** [comment]
Hi Chris.
Thanks. You welcome
