### ISSUE TITLE
Deleting member doesn't actually delete member

### ISSUE THREAD

**Issue by AllardStruiksma** [Uintra/Uintra#60]
Hello,

I have added a few members in Uintra.
When i try to delete a member, it still remains in the list of members.
It's also still visible in the database.
Any idea what the issue is and how it can be fixed?

**Comment by denprodan** [comment]
Hello there. Yes that's correct behavior. Uintra didn't allow to delete members physically from db by default. So if you delete member it will be marked as inactive in Umbraco and UI (if this member makes some activities)
