### ISSUE TITLE
Can't extend navigation panel

### ISSUE THREAD

**Issue by MiguelIPerez** [Uintra/Uintra#7]
Hi guys,

I am new to uintra, and, i got a new requeriment that says that the app need to some custom buttons on the panel, like the ones highlighted.
![image](https://user-images.githubusercontent.com/36245944/49150407-ccf1ef80-f2da-11e8-8e38-1be16dba5e30.png)

I already creted the "controller" the "view" and the "Model" but, every time i run mi code it keep throwing me this error:

"### **

> No physical template file was found for template LeftNavigation

**"
is like i am missing something but i dont know what.

does anybody face the same problem or know how to propely add new buttons to the nav panes

thank you much

**Comment by MiguelIPerez** [comment]
yes those buttons lead to content pages

**Comment by denprodan** [comment]
It's easy
Your User has to be in Administartor role
Just go to the Umbraco backoffice and add new Conten Page
![image](https://user-images.githubusercontent.com/25720118/49152744-71e0ec80-f31c-11e8-8774-078760013b5d.png)
Then fill all required properties
![image](https://user-images.githubusercontent.com/25720118/49152844-b4a2c480-f31c-11e8-85f0-4ca4a43afe58.png)
![image](https://user-images.githubusercontent.com/25720118/49152942-f2075200-f31c-11e8-9c0e-ecf3a79e4dab.png)
![image](https://user-images.githubusercontent.com/25720118/49152970-02b7c800-f31d-11e8-8e64-7ce4abb954cf.png)

**Comment by MiguelIPerez** [comment]
Yeah!! it worked thank you so much, that was exactly what i need it!

**Comment by denprodan** [comment]
You welcome. Don't hesitate to contact with us if you have any questions about Uintra
