### ISSUE TITLE
How to add the User List Page

### ISSUE THREAD

**Issue by Cookzenberg** [Uintra/Uintra#8]
I upgraded from 0.5 to 1.0.0.1 and wanted to install the User List functionality to the top bar as you have on the demo site. 

I edit the Home page, and select the Navigation tab, and click the Add button in the User List Page box.

A window appears on the right to allow me to select some content, but all the items in there are disabled.

Do I need to create a content page myself or am I missing something else?

Apologies but I'm new to Umbraco so this may be the start of some dumb questions!

**Comment by denprodan** [comment]
Hi Cookzenberg
Could you please provide screenshots?

**Comment by Cookzenberg** [comment]
Please find attached.

**Comment by Cookzenberg** [comment]
Gah... Firefox. One moment.

**Comment by Cookzenberg** [comment]
![userlist](https://user-images.githubusercontent.com/29954530/49404829-7e17e000-f748-11e8-9768-468313a1626f.png)

Please see attached.

**Comment by denprodan** [comment]
Hi Cookzenberg
First of all you have to create new conten page in Content section
![image](https://user-images.githubusercontent.com/25720118/49427592-59edea80-f7ac-11e8-91de-fb0c58cc03e5.png)
Then in new content page add user list panel
![image](https://user-images.githubusercontent.com/25720118/49427680-9de0ef80-f7ac-11e8-8214-d5f2811d659a.png)
And only after that you can choose Navigation Tab at Home page and point user lists button to your new content page with user list panel on it
![image](https://user-images.githubusercontent.com/25720118/49427757-e00a3100-f7ac-11e8-8283-557d95b42944.png)

**Comment by Cookzenberg** [comment]
Ok thanks. I did that but omitted to add the three fields (Photo, Name, Email) to the Users page so of course it was blank when launched from the navbar. 

After I added those the data is visible.

I also added an "order by" column but the names are sorted in descending order (z-a). I don't see any way in the Umbraco settings to change this?

**Comment by denprodan** [comment]
So generally user lists works and show results?
Could you please close this task and create another one related to this bug
Thanks in advance

**Comment by Cookzenberg** [comment]
Yes thanks. Closing.
