### ISSUE TITLE
NullReferenceException: Compent.Uintra.Controllers.CentralFeedController.GetCentralFeedItems

### ISSUE THREAD

**Issue by AllardStruiksma** [Uintra/Uintra#95]
Hello,

We've been using Uintra for about half a year now and suddenly this morning we've been getting a nullreference exception. This exception gets thrown every 30 seconds. When i log into Uintra everything seems to be working fine. I tried restarting the application pool but the exception keeps getting thrown. 

This is the stacktrace:
System.NullReferenceException: Object reference not set to an instance of an object.
at Compent.Uintra.Controllers.CentralFeedController.GetCentralFeedItems
at Uintra.CentralFeed.Web.CentralFeedControllerBase.List
at System.Web.Mvc.ActionMethodDispatcher.Execute
at System.Web.Mvc.ReflectedActionDescriptor.Execute
at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod
at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39
at WrappedAsyncResult`2.CallEndDelegate
at WrappedAsyncResultBase`1.End
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod
at AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f
at <>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32
at WrappedAsyncResult`1.CallEndDelegate
at WrappedAsyncResultBase`1.End
at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters
at <>c__DisplayClass2b.<BeginInvokeAction>b__1c
at <>c__DisplayClass21.<BeginInvokeAction>b__1e

Do you have any idea what could be causing this?

**Comment by denprodan** [comment]
Hi @AllardStruiksma Did you try to attach to the process? It's look like some of your activities return null
